### ISSUE TITLE
Could we see support for UPBGE 3.0?

### ISSUE THREAD

**Issue by ItsCubeTime** [nutti/fake-bge-module#3]
Could we see support for UPBGE 3.0?

**Comment by nutti** [comment]
UPBGE has not released 3.0 yet.
I will release this one after 3.0 is released.

And I consider to support daily release same as [fake-bpy-module](https://pypi.org/project/fake-bpy-module-latest/).

**Comment by nutti** [comment]
@ItsCubeTime 

Now, the daily build version of fake-bge-module is released.
https://pypi.org/manage/project/fake-bge-module-latest/releases/

You can try this for the latest UPBGE version including 0.3.

**Comment by ItsCubeTime** [comment]
> @ItsCubeTime
> 
> Now, the daily build version of fake-bge-module is released.
https://pypi.org/manage/project/fake-bge-module-latest/releases/
> 
> You can try this for the latest UPBGE version including 0.3.

Thanks a bunch 💝
